# Generated by Django 5.2.1 on 2025-07-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0004_alter_exchangecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironIssueData',
            fields=[
                ('environ_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('environ_data_title', models.CharField(max_length=50, verbose_name='환경데이터 제목')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='등록일')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.nation')),
            ],
            options={
                'verbose_name_plural': '[공공데이터] (환경이슈관련 모델) EnvironIssueDatas',
            },
        ),
    ]
