# Generated by Django 5.2.1 on 2025-07-01 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0004_alter_exchangecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('opinion_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='의견 제목')),
                ('content', models.TextField(verbose_name='의견 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.localgoverment')),
            ],
        ),
    ]
