# Generated by Django 5.2.1 on 2025-07-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
        ('status', '0004_alter_exchangecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=50, verbose_name='행사명')),
                ('program_content', models.TextField(verbose_name='행사 내용')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.localgoverment')),
            ],
        ),
    ]
