# Generated by Django 5.2.1 on 2025-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='title',
            field=models.TextField(verbose_name='의견 제목'),
        ),
    ]
