# Generated by Django 5.2.1 on 2025-07-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0004_alter_exchangecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TendData',
            fields=[
                ('tend_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('health', '보건/환경/기술'), ('edu', '교육/역량강화'), ('culture', '문화/공공외교'), ('system', '제도/행정/포용'), ('etc', '기타')], default='etc', max_length=50)),
                ('title_kr', models.CharField(max_length=30, verbose_name='국가최신동향 제목(국문)')),
                ('title_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='국가최신동향 제목(영문)')),
                ('content_kr', models.TextField(blank=True, null=True, verbose_name='국가최신동향 내용(국문)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='국가최신동향 내용(영문)')),
                ('pub_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='국가최신동향 게시일')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.nation')),
            ],
        ),
    ]
