# Generated by Django 5.2.1 on 2025-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movementdata_delete_tenddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomacyEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=50, verbose_name='행사 제목')),
                ('event_category', models.CharField(max_length=30, verbose_name='행사 분류')),
                ('event_content', models.TextField(verbose_name='행사 내용')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '(공공외교행사 모델) DiplomacyEvents',
            },
        ),
        migrations.AlterModelOptions(
            name='movementdata',
            options={'verbose_name_plural': '[공공데이터] (최신동향 모델) MovementDatas'},
        ),
    ]
