# Generated by Django 5.2.1 on 2025-07-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_diplomacyevent_alter_movementdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementdata',
            name='nation_type',
            field=models.CharField(choices=[('donor', '공여국'), ('recipient', '수원국'), ('etc', '기타')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movementdata',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
