# Generated by Django 5.2.1 on 2025-07-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movementdata_nation_type_alter_movementdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementdata',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movementdata',
            name='nation_type',
            field=models.CharField(blank=True, choices=[('donor', '공여국'), ('recipient', '수원국'), ('etc', '기타')], max_length=50, null=True),
        ),
    ]
