# Generated by Django 5.2.1 on 2025-06-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGoverment',
            fields=[
                ('local_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_name', models.CharField(max_length=50, verbose_name='지방자치단체 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('nation_id', models.AutoField(primary_key=True, serialize=False)),
                ('nation_name', models.CharField(max_length=20, verbose_name='국가 이름')),
                ('nation_info', models.TextField(verbose_name='국가 정보')),
            ],
        ),
        migrations.CreateModel(
            name='LocalDashboard',
            fields=[
                ('local_dash_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_map_explain', models.TextField(verbose_name='교류 현황 설명')),
                ('local_sister_explain', models.TextField(verbose_name='자매도시 설명')),
                ('local_friendly_explain', models.TextField(verbose_name='우호 결연 도시 설명')),
                ('local_ratio_explain', models.TextField(verbose_name='주요 교류국 순위 설명')),
                ('local_ratio_explain_detail', models.TextField(verbose_name='주요 교류국 순위 상세 설명')),
                ('local_category_explain', models.TextField(verbose_name='주요 교류 분야 설명')),
                ('local_vision_explain', models.TextField(verbose_name='비전 설명')),
                ('local', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.localgoverment')),
            ],
        ),
        migrations.CreateModel(
            name='NationDashboard',
            fields=[
                ('nation_dash_id', models.AutoField(primary_key=True, serialize=False)),
                ('nation_map_explain', models.TextField(verbose_name='교류 현황 설명')),
                ('nation_ratio_explain', models.TextField(verbose_name='분야별 교류 비율 설명')),
                ('nation_ratio_explain_detail', models.TextField(verbose_name='분야별 교류 비율 상세 설명')),
                ('nation_recent_explain', models.TextField(verbose_name='최근 교류 사례 설명')),
                ('nation_num_tend', models.TextField(verbose_name='교류 사업 수 추이 설명')),
                ('nation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.nation')),
            ],
        ),
    ]
