# Generated by Django 5.2.1 on 2025-06-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeData',
            fields=[
                ('exchange_id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_name_kr', models.CharField(blank=True, max_length=100, null=True, verbose_name='교류 데이터 국문 이름')),
                ('exchange_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='교류 데이터 영문 이름')),
                ('exchange_category', models.CharField(blank=True, choices=[('health', '보건/환경/기술'), ('edu', '교육/역량강화'), ('culture', '문화/공공외교'), ('system', '제도/행정/포용'), ('etc', '기타')], default='etc', max_length=50, null=True, verbose_name='분야')),
                ('exchange_content', models.TextField(blank=True, null=True, verbose_name='교류 데이터 내용')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='시작 연도')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='종료 연도')),
                ('others', models.TextField(verbose_name='기타사항')),
                ('pub_date', models.DateField(verbose_name='등록일')),
                ('exchange_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.nation')),
            ],
        ),
    ]
