# Generated by Django 5.2.1 on 2025-07-01 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_exchangedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalData',
            fields=[
                ('local_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_country', models.CharField(max_length=50, verbose_name='대상 국가')),
                ('partner_city', models.CharField(max_length=70, verbose_name='대상 도시')),
                ('category', models.CharField(choices=[('sister', '자매도시'), ('friendly', '우호결연 도시')], max_length=50, verbose_name='도시 구분')),
                ('agreement_date', models.DateField(verbose_name='결연일자')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.localgoverment')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('vision_id', models.AutoField(primary_key=True, serialize=False)),
                ('vision_category', models.CharField(max_length=30, verbose_name='분류')),
                ('vision_title', models.CharField(max_length=50, verbose_name='제목')),
                ('vision_content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.localgoverment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(choices=[('health', '보건/환경/기술'), ('edu', '교육/역량강화'), ('culture', '문화/공공외교'), ('system', '제도/행정/포용'), ('etc', '기타')], max_length=50, verbose_name='교류 분야 이름')),
                ('exchange_num', models.PositiveIntegerField(verbose_name='교류 분야 수(또는 순위)')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_category_relations', to='status.localgoverment')),
            ],
            options={
                'unique_together': {('local', 'exchange_name')},
            },
        ),
    ]
