# Generated by Django 5.2.1 on 2025-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_localdata_vision_exchangecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangecategory',
            options={'verbose_name_plural': '(지자체관련 모델) ExchangeCategories'},
        ),
        migrations.AlterModelOptions(
            name='exchangedata',
            options={'verbose_name_plural': '[공공데이터] (국가관련 모델) ExchangeDatas'},
        ),
        migrations.AlterModelOptions(
            name='localdashboard',
            options={'verbose_name_plural': '(지자체관련 모델) LocalDashboards'},
        ),
        migrations.AlterModelOptions(
            name='localdata',
            options={'verbose_name_plural': '[공공데이터] (지자체관련 모델) LocalDatas'},
        ),
        migrations.AlterModelOptions(
            name='localgoverment',
            options={'verbose_name_plural': '(지자체관련 모델) LocalGoverments'},
        ),
        migrations.AlterModelOptions(
            name='nation',
            options={'verbose_name_plural': '(국가관련 모델) Nations'},
        ),
        migrations.AlterModelOptions(
            name='nationdashboard',
            options={'verbose_name_plural': '(국가관련 모델) NationDashboards'},
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '(지자체관련 모델) Visions'},
        ),
        migrations.RemoveField(
            model_name='exchangecategory',
            name='id',
        ),
        migrations.AddField(
            model_name='exchangecategory',
            name='exchange_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
