# Generated by Django 5.2.1 on 2025-07-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_exchangecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedata',
            name='others',
            field=models.TextField(blank=True, null=True, verbose_name='기타사항'),
        ),
        migrations.AlterField(
            model_name='exchangedata',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='등록일'),
        ),
    ]
