# Generated by Django 5.2.1 on 2025-07-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_alter_exchangedata_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='nation_economic',
            field=models.TextField(blank=True, null=True, verbose_name='국가 경제현황'),
        ),
        migrations.AddField(
            model_name='nation',
            name='nation_relation',
            field=models.TextField(blank=True, null=True, verbose_name='우리나라와의 관계'),
        ),
    ]
